package com.vtech.app.largeuidb.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.vtech.app.largeuidb.largeuibean.ContactsBean;
import com.vtech.app.largeuidb.largeuibean.LargeUIItem;

import com.vtech.app.largeuidb.db.ContactsBeanDao;
import com.vtech.app.largeuidb.db.LargeUIItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactsBeanDaoConfig;
    private final DaoConfig largeUIItemDaoConfig;

    private final ContactsBeanDao contactsBeanDao;
    private final LargeUIItemDao largeUIItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactsBeanDaoConfig = daoConfigMap.get(ContactsBeanDao.class).clone();
        contactsBeanDaoConfig.initIdentityScope(type);

        largeUIItemDaoConfig = daoConfigMap.get(LargeUIItemDao.class).clone();
        largeUIItemDaoConfig.initIdentityScope(type);

        contactsBeanDao = new ContactsBeanDao(contactsBeanDaoConfig, this);
        largeUIItemDao = new LargeUIItemDao(largeUIItemDaoConfig, this);

        registerDao(ContactsBean.class, contactsBeanDao);
        registerDao(LargeUIItem.class, largeUIItemDao);
    }
    
    public void clear() {
        contactsBeanDaoConfig.clearIdentityScope();
        largeUIItemDaoConfig.clearIdentityScope();
    }

    public ContactsBeanDao getContactsBeanDao() {
        return contactsBeanDao;
    }

    public LargeUIItemDao getLargeUIItemDao() {
        return largeUIItemDao;
    }

}
